### ISSUE TITLE
"max() arg” error occurs when running with data shipped with code

### ISSUE THREAD

**Issue by kwhitehall** [kwhitehall/grab-tag-graph#106]
Thanks to @diegovb for reporting.

Error received is shown below
-------------- findMCCs ----------
Traceback (most recent call last):
  File "mccSearchUI.py", line 199, in <module>
    main()
  File "mccSearchUI.py", line 65, in main
    MCCList,MCSList = mccSearch.find_MCC(prunedGraph,userVariables,graphVariables)
  File ".../code/mccSearch.py", line 855, in find_MCC
    MCCList = checked_nodes_MCC(prunedGraph, treeTraversalList, userVariables,graphVariables)
  File ".../code/mccSearch.py", line 1034, in checked_nodes_MCC
    cloudElementAreaA, _ = check_criteria(thisdict['cloudElementLatLon'], userVariables.OUTER_CLOUD_SHIELD_TEMPERATURE, userVariables)
  File ".../code/mccSearch.py", line 1508, in check_criteria
    return  max(allCriteriaB, key=lambda x:x[0]) #if allCriteriaB != [] else cloudElementArea, cloudElementCriteriaBLatLon
ValueError: max() arg is an empty sequence

**Comment by kwhitehall** [comment]
Fixed with PR #107. @diegovb  can you please test it out?

**Comment by diegovb** [comment]
I will test this later today

**Comment by diegovb** [comment]
Working for both @marcuseng and me

**Comment by kwhitehall** [comment]
thanks @diegovb  and @marcuseng!
