### ISSUE TITLE
Initial pass at linting utils.py

### ISSUE THREAD

**Issue by cgoodale** [kwhitehall/grab-tag-graph#20]
The initial plan is to clean up whitespace and remove un-used variables.

I am also considering refactoring some of the logic within the validDate function, so we have only one return statement.

**Comment by cgoodale** [comment]
It appears I have a little more work to do since I have read up on the Code Readability Page.

Thanks for the guidance @kwhitehall :)

**Comment by kwhitehall** [comment]
@cgoodale  sorry about that! I figure you are still working on that bit of code ...
