### ISSUE TITLE
Refactor the utils.validDate function

### ISSUE THREAD

**Issue by cgoodale** [kwhitehall/grab-tag-graph#22]
While linting the utils.py module I came across this function and i wanted to work on it, but didn't want to mix simple code linting with actually changing the logic of the function.
# Plan of attack:
-  Write up a set of tests to clearly define the function's behavior
-  Refactor the internal code to make it more readable.  I think python's datetime module will prove useful helper methods.
-  I would like to have the function return a boolean instead of a status code of 0 or 1 in the future.  To support this all other callers will need to check for a boolean instead of an int as the return value.

**Comment by kwhitehall** [comment]
Sounds good @cgoodale. Also please see issue #23 I'll be uploading shortly.. just fixing one last configuration.. took a little while to go through the PyLint docs

**Comment by cgoodale** [comment]
Hey @kwhitehall I see that in other code you are using the returned value of 1 or 0 to enable a while loop to wait for a valid response.

I have a pretty simple solution using the datetime.datetime.strptime() function.  The catch is that when something comes into the function incorrectly it will raise an exception instead of returning a 0.

I will look at how to keep the while loop construct in place while using the strptime() function.  PR should be coming in a few and we can discuss more then.

**Comment by kwhitehall** [comment]
Kool scene @cgoodale. Thanks for the heads up!
