### ISSUE TITLE
Next stage of refactoring

### ISSUE THREAD

**Issue by kwhitehall** [kwhitehall/grab-tag-graph#32]
Discussion on the best ways to move forward refactoring this code.

**Comment by kwhitehall** [comment]
@cgoodale @chrismattmann @lewismc 
My suggestion is to succinctly write the existing functions. But I wonder should we discuss full out architecture design and how "global variables" from the initial code are being passed around  and look into creating objects?

**Comment by cgoodale** [comment]
My preference is to break the functionality into smaller succinct functions as a next step, and cover them with unit tests.  In a longer timeline, having small functions will enable them to move into being methods on objects.

If you already know which objects make best sense in this code base, then we could skip the small function step and start porting code into methods on the objects, but I have no clue what objects make sense at this time.

**Comment by kwhitehall** [comment]
I'm not 100% of the objects. Linting through the code there are some functions that are a bit too long... so I agree it may be worth while to break them up first and test away. 

Do you think it useful to meet/Hangout for an end to end running of the code (once issue 7 is resolved)?  In the meantime feel free to checkout the wiki pages https://github.com/kwhitehall/grab-tag-graph/wiki/Using-GTG (especially the workflow section) and https://github.com/kwhitehall/grab-tag-graph/wiki/File-structure-and-function-distribution-in-GTG

**Comment by lewismc** [comment]
Hi Kim,
I'll take a look later today and pass an opinion.
Ta

On Sunday, May 17, 2015, Kim Whitehall notifications@github.com wrote:

> I'm not 100% of the objects. Linting through the code there are some
> functions that are a bit too long... so I agree it may be worth while to
> break them up first and test away.
> 
> Do you think it useful to meet/Hangout for an end to end running of the
> code (once issue 7 is resolved)? In the meantime feel free to checkout the
> wiki pages https://github.com/kwhitehall/grab-tag-graph/wiki/Using-GTG
> (especially the workflow section) and
> https://github.com/kwhitehall/grab-tag-graph/wiki/File-structure-and-function-distribution-in-GTG
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/kwhitehall/grab-tag-graph/issues/32#issuecomment-102922967
> .

## 

_Lewis_

**Comment by kwhitehall** [comment]
Hey guys issue #7  is closed with PR #33 (w00t!). Big THANK YOU to @cgoodale for your efforts getting us here!!! In bajan terms, I feel so fussy right now :-)
@cgoodale I'm ok with your suggestion for the next step. I think it might be prudent to follow the workflow that organically grew in refactoring phase II. i.e. (1) open an umbrella issue (something like "Refactoring phase III - succinctly rewriting functions"), (2) keep that open until we are completed with the process, and (3) open smaller issues towards refactoring phase III as seen fit, linking the issues as necessary to the umbrella issue. Thoughts?

**Comment by chrismattmann** [comment]
+1 from me @kwhitehall and @cgoodale . My general feeling related to this is that I prefer OO style of design and/or at least modules with globals that are imported when needed and reset when needed too.

**Comment by kwhitehall** [comment]
Hey guys, I'm closing this convo. Thanks for the discussions that lead to our conclusions & future actions.
