### ISSUE TITLE
utils.find_time isn't being used?

### ISSUE THREAD

**Issue by cgoodale** [kwhitehall/grab-tag-graph#34]
Hey @kwhitehall I was looking for another chance to work on the utils.py code and I was going to clean up the find_time function, but before I started I wanted to see how it was being called.  Turns out it isn't being called anymore (at least not according to a quick grep through the code base).

Can you take a look and make sure I am not missing something?

Thanks

**Comment by kwhitehall** [comment]
Hey @cgoodale, that function existed initially to check for correct files. It looks like the functionality was slurped into the function check_for_files in iomethods.py leveraging the datetime object. 
In terms of a use case, I'm not entirely convinced that such functionality would not be needed for other purposes e.g. in the plotting module. 
I'll suggest for now the following (and this can be done for any other function found that seem not to be used): move the function the bottom of the file  and comment it out under a heading deprecated. 
In the next refactoring round, if we realize that there really is no need for them we'll remove those deprecated functions from the code base. Thoughts?

**Comment by cgoodale** [comment]
That makes sense to me.  I will send a PR shortly.

**Comment by kwhitehall** [comment]
Merge PR #35. Resolve issue #34.
