### ISSUE TITLE
Error in traverseTree function for one month run

### ISSUE THREAD

**Issue by nurfee** [kwhitehall/grab-tag-graph#41]
Hello, I'm Gita. I have a modified version of "older" GTG (https://github.com/nurfee/grab-tag-graph/tree/mcs_modified_dataset/code) and I've been trying to run a sensitivity test using this.

I intend to investigate the influence of data spatial resolution to MCS identification. I resampled the MTSAT hourly data from 4 km to 8 km (here is the data in 8 km resolution: https://drive.google.com/folderview?id=0B8INNzOUyo-oTnF1RDQ1bHhkc28&usp=sharing). If the results don't differ much, then I will use the resampled dataset in the future to save computational time since I need to run the code for a quite long time span, at least about one year.

I chose the case during February 2007 (neutral condition for ENSO and IOD, but with presence of MJO). For starters, I used criteria from Williams and Houze (1987) for TBB (213 K) and 5000 km^2 for defining a cloud element. It worked well for Indonesian region (1502 x 702 grids for 4 km resolution; 751 x 376 grids for 8 km resolution). However when I changed the T_BB_MAX to 235 K, even for the 8 km resolution it stopped working. It was said "maximum recursion depth exceeded" (I put some parts of the log in my github: https://github.com/nurfee/grab-tag-graph/blob/mcs_modified_dataset/code/log.T235AL3S8P60).

Is it possible to overcome this issue?
Thanks.

Gita

**Comment by kwhitehall** [comment]
Hi @nurfee! Thank you for your issue. We'll take a close look at it and get back to you shortly.

**Comment by kwhitehall** [comment]
The immediate feedback of this problem is to increase the recursion limit in python like so
import sys 
sys.setrecursionlimit(####)
by default is in @1000
See http://pythontips.com/2013/08/31/fixing-error-maximum-recursion-depth-reached/ for more info.
@nurfee thank you for your offline feedback with regards to the success of this solution.

**Comment by kwhitehall** [comment]
The system setting was added into GTG with x5 the limit being set. However, the problem of performance of the code and parallelization still are to be address to truly address this issue. 
Partially resolved with merge #52.
