### ISSUE TITLE
Youssef's Tasks for Grab-Tag-Graph Code

### ISSUE THREAD

**Issue by youssefbiaz** [kwhitehall/grab-tag-graph#44]
- Develop a user interface to run the algorithm on data with adequate real-time visualization
- Work closely with Haig to incorporate generated visualization into the interface

**Comment by kwhitehall** [comment]
Hey Youssef, 
In general for this task, we will utilize Jupyter Notebooks (formally iPython notebooks)

For the next two wks can you work on the following?
*Create an object for the user-defined variables (keep in mind backward compatibility). See lines 21-53 of mccSearch.py. Use the current settings as the defaults
- Brainstorm how to how to get these vars from the user
  - Categorize importance accordingly to user-variability (I can help with this)

**Comment by kwhitehall** [comment]
This issue has been closed with PR #82. Thank you @youssefbiaz for your hard work on this!
