### ISSUE TITLE
Jacob's Goals (USC Capstone Project Fall 2015)

### ISSUE THREAD

**Issue by Jacobliber** [kwhitehall/grab-tag-graph#45]
- Contribute towards the SciSpark project in order to leverage the Apache Spark cluster computing framework to improve the speed of computation of the GTG algorithm
  (https://github.com/rahulpalamuttam/SciSpark)
- Collaborate with USC Capstone Project team on parallelizing/refactoring the GTG source code in order to more fully take advantage of local hardware (e.g. laptop, desktop and off-the-shelf small server systems) processing capacity

**Comment by kwhitehall** [comment]
Nice one Jacob,
Please focus on the find_MCC function from mccSearch.py for implementation into SciSpark.

**Comment by kwhitehall** [comment]
Thanks for your contributions to these two projects @Jacobliber! I'm closing off this issue now as the course is over. @cgoodale
