### ISSUE TITLE
Haig's Goals for Grab-Tag-Graph Code

### ISSUE THREAD

**Issue by HaigNalbandian** [kwhitehall/grab-tag-graph#46]
- Eliminate ambiguity during the running of the program by providing the user with visualizations of the data being generated and interpreted. My first step will be leveraging existing Python visualization libraries (namely Bokeh).
- Work with Youssef in integrating these visuals into a clean and user-friendly graphical interface.
- As a secondary interest, keeping up with the algorithmic improvements being made and contributing anything that could be useful.

**Comment by kwhitehall** [comment]
Hey Haig, nice description. For the first bullet point can you work on delivering the following?
- Demonstrate the real-time detection of the cloud elements in find_cloud_elements function in a Bokeh server.
- Use the variable cloudElementArea

**Comment by cgoodale** [comment]
@haigonlife I put together a simple mockup to help demonstrate what @kwhitehall and I have been discussing.

![cloudelementviz_draft](https://cloud.githubusercontent.com/assets/750420/10052514/45dd92d4-61dc-11e5-8e3c-66051ad92fcf.png)

**Comment by kwhitehall** [comment]
Hi @haigonlife, thanks for your contributions on this project. I'm closing off this issue as the course is over now. @cgoodale
