### ISSUE TITLE
Gabe's goals for GTG

### ISSUE THREAD

**Issue by meldefon** [kwhitehall/grab-tag-graph#47]
This semester, the overarching goal will be to speed the code up. This will occur in two linked phases:

I. Serial optimization - my primary focus, and will be aimed at speeding up the code in its current serial form. Steps include:
- Gaining a familiarity with GTG and its current python implementation
- Addressing possible code inefficiencies
- Improving the underlying serial algorithm run-time efficiency without changing results

II. Parallelization - I'll also provide input and code to team members who are working specifically on speeding up the code with parallelism. This will include:
- Redesigning the algorithm to run more efficiently on parallel architectures
- Implementing core- and server-parallel versions of the code

As far as issue 1 goes, I've already started reading the code carefully and now understand the high-level flow of the code, as well as the implementation details of some of the algorithm's sub-pieces. After doing a basic profiling of the code, I've decided that I'll begin by focusing efforts on find_cloud_elements in mccSearch.py, which is where many of the algorithm's main steps occur, and where most of the runtime is spent. 
I've also begun thinking about how to take advantage of parallel hardware. I have a few ideas for parallel implementation of certain steps, and will discuss them with Jacob in more detail soon.

**Comment by kwhitehall** [comment]
Hey Gabe, 
I agree with starting with find_cloud_elements in mccSearch.py
Your on the serial optimization for now is a great start. 
- Please refactor that function into subsections e.g. between lines 355 - 376 and 435-55 are i/o items that can be pulled out into a separate function. Please remember to provide unittests where necessary.
- Profile again after the refactoring 
- Provide an approach to reduce the inefficient section(s) found (serially or otherwise)

**Comment by meldefon** [comment]
@kwhitehall I've pushed a brief write-up of my progress over the last few days. It's in my repo in writeupOct5. Link: https://github.com/meldefon/grab-tag-graph/blob/master/writeupOct5

**Comment by kwhitehall** [comment]
Thanks for the update @meldefon! Can you please push the optimizations done thus far as a PR?

**Comment by meldefon** [comment]
@kwhitehall No problem! I'll push that up ASAP.

**Comment by kwhitehall** [comment]
These updates have been merged into the codebase with PR #81. Thank you @meldefon for your contributions!
