### ISSUE TITLE
Setting up a fresh install on OS X shows we have some old installation instructions

### ISSUE THREAD

**Issue by cgoodale** [kwhitehall/grab-tag-graph#55]
I will push up some changes to the Home wiki page about Anaconda version and how to get things installed on OS X 10.10 Yosemite.

**Comment by cgoodale** [comment]
@kwhitehall I don't see anyway to create a PR for the wiki.  If you wouldn't mind opening up the wiki so I can push my edits directly to it, that would be swell.  If you'd rather keep it locked down I send send you a diff to patch your local copy.

Let me know how to proceed.

Thanks

**Comment by cgoodale** [comment]
Below is the basic content change I am proposing.
- Python 2.7.x (We used Anaconda 2.3.0 64 bit libraries, which installs the following dependencies.)
- sciPy
- NumPy
- Networkx
- matplotlib

Other module dependences:
- netCDF4
- GrADS (We used OpenGrADS grads2 Version 2.0.1.oga.1)
  - LATS4D
    A user of the code noted that if you are GrADs v.2.1.a2 your image output format will have to be changed from .gif to .png if you receive the following error "GXPRINT error: unsupported output format"
  
  ### Mac OS X 10.10 Installation Steps
  - Install [Anaconda](http://continuum.io/downloads) from Continuum Analytics
  - Install [Homebrew](http://brew.sh/)
  - Install HDF5 using homebrew:
  
  ``` bash
  brew tap homebrew/science
  brew install hdf5
  ```
  - Use pip to install netCDF4
  
  ``` bash
  pip install netCDF4
  ```

**Comment by kwhitehall** [comment]
Hi @cgoodale, thank you for the update to the installation instructions. I've added you as a collaborator on the project, so feel free to edit away :-) Thank you for your continued contributions.

**Comment by cgoodale** [comment]
I pushed up my changes and will close this issue.  Let me know if I should make any other changes.  Thanks @kwhitehall.
