### ISSUE TITLE
Refactoring Phase II - variable names and function names in mccSearch.py

### ISSUE THREAD

**Issue by kwhitehall** [kwhitehall/grab-tag-graph#7]
work on renaming the variable and function names to generic names that represent the functionality. Update documentation accordingly

**Comment by cgoodale** [comment]
Hey Kim I was diving into this file mccSearch.py and I have found an un-used variable called: CEprecipRate.

This has been commented out in places, and it is left in place in others.  I can see the variable being called out 4 times, but it doesn't appear to be in use anymore.

When I started to comment the variable out entirely it started a chain reaction in the code base where many other input variables are no longer needed is CEprecipRate is removed, such as all the latLon's used to define CEprecipRate.

Looks like the code used to have support for TRMM data, which is might still have, but this variable isn't being used so I would like to remove it.  (Less to maintain ;)

**Comment by kwhitehall** [comment]
@cgoodale CEprecipRate can be removed (it is a residual from a first attempt I was doing). Indeed, the TRMM data is still supported through the functions. Also, I agree the variables latStartT, latEndT, lonStartT, lonEndT, latStartIndex, latEndIndex, lonStartIndex, lonEndIndex can also be removed 

Thanks for highlighting the issue. Unfortunately, I'm sure we'll find many more of such cases as this code is refactored.

**Comment by chrismattmann** [comment]
Seen @kwhitehall @cgoodale

**Comment by cgoodale** [comment]
Hey @kwhitehall I have a work-in-progress PR coming shortly, in the meantime i was trying to clean up all of the other un-used variables and I came across the following.

``` bash
~/grab-tag-graph/code(lint_mcc_search) $ pylint mccSearch.py | grep undefined-variable
No config file found, using default configuration
E:535,20: Undefined variable 'LAT' (undefined-variable)
E:536,20: Undefined variable 'LON' (undefined-variable)
E:542,83: Undefined variable 'LAT' (undefined-variable)
E:542,88: Undefined variable 'LON' (undefined-variable)
E:556,54: Undefined variable 'LAT' (undefined-variable)
E:557,54: Undefined variable 'LON' (undefined-variable)
E:567,23: Undefined variable 'LON' (undefined-variable)
E:571,23: Undefined variable 'LAT' (undefined-variable)
E:581,86: Undefined variable 'LAT' (undefined-variable)
E:581,96: Undefined variable 'LAT' (undefined-variable)
E:581,132: Undefined variable 'LON' (undefined-variable)
E:581,142: Undefined variable 'LON' (undefined-variable)
E:1362,28: Undefined variable 'LAT' (undefined-variable)
E:1363,28: Undefined variable 'LAT' (undefined-variable)
E:1364,28: Undefined variable 'LON' (undefined-variable)
E:1365,28: Undefined variable 'LON' (undefined-variable)
E:1372,34: Undefined variable 'LAT' (undefined-variable)
E:1372,78: Undefined variable 'LON' (undefined-variable)
E:1410,33: Undefined variable 'LAT' (undefined-variable)
E:1410,47: Undefined variable 'LON' (undefined-variable)
|undefined-variable         |20          |
```

Around line 533 I left a TODO about how to handle these variables, seems to me LATTRMM and LONTRMM would be replacements until some functions use LAT and LATTRMM as inputs, so it starts to break down a bit.

**Comment by chrismattmann** [comment]
Yolo

**Comment by kwhitehall** [comment]
@cgoodale I'm tackling this now most of the basic linting is done on the files. I'll update mccsearchUI.py with this one as well. When this issue is closed, we will know we have completed all of Refactoring Phase 2 for all the python files in the GTG code based. For completeness:
(1) refactoring Phase 1 was dividing up the original large file mccSearch.py into files with functions that contained similar utility 
(2) refactoring Phase 2 is linting of these files to ensure they met the GTG lint convention as outlined by the wiki.
We have to discuss the next steps of refactoring this code. I'm tempted to say succinctly writing the existing functions? Should we talk full out architecture design and how "global variables" from the initial code are being passed around? Look into creating objects? I'm going to open a new issue on this for us to port the that discussion there.

**Comment by kwhitehall** [comment]
Yippie! Looks like phase II of refactoring is finished @cgoodale!!!

**Comment by chrismattmann** [comment]
ack
