### ISSUE TITLE
Updating Wiki Documentation

### ISSUE THREAD

**Issue by meldefon** [kwhitehall/grab-tag-graph#76]
@kwhitehall  Here's a slide which shows the function call flow in @meldefon's current implementation
[Parallel_version_flow.pdf](https://github.com/kwhitehall/grab-tag-graph/files/36207/Parallel_version_flow.pdf)

**Comment by kwhitehall** [comment]
Thanks @meldefon!

**Comment by kwhitehall** [comment]
@meldefon This has been added by updating the documentation on https://github.com/kwhitehall/grab-tag-graph/wiki/Using-GTG.  This update closes this issue. 
Thank you for your contribution!
