### ISSUE TITLE
Update document to include how to use the notebook. 

### ISSUE THREAD

**Issue by kwhitehall** [kwhitehall/grab-tag-graph#85]
Add on the wiki with screenshots.

**Comment by cgoodale** [comment]
@kwhitehall Please review https://github.com/kwhitehall/grab-tag-graph/wiki/Quick-Start---GTG-Jupyter-Notebook and comment or close this issue accordingly.  Sorry it took so long to get it pulled together.

**Comment by kwhitehall** [comment]
@cgoodale This is sweet! Thanks dude! 
To end the document, maybe a "Successful run" heading with a screenshot of a Finder window (list view) with the folders create at the location b the GTG and the files. I can do this quickly.

**Comment by kwhitehall** [comment]
Updated. I just added a sentence instead of a heading to keep up with the style of the document. Thanks for taking on that documentation @cgoodale !
